apiVersion: v1
kind: Service
metadata:
  labels:
    app: rq-exporter
  name: rq-exporter
  namespace: monitoring
spec:
  ports:
    - name: "9726"
      port: 9726
      targetPort: 9726
  selector:
    app: rq-exporter
  #clusterIP: None
status:
  loadBalancer: {}
