apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rq-exporter-metrics
  namespace: monitoring
  labels:
    app: rq-exporter
    release: monitoring
spec:
  selector:
    matchLabels:
      app: rq-exporter
      release: monitoring
  endpoints:
  - interval: 5s
    path: /
    port: "9726"
  namespaceSelector:
    matchNames:
      - monitoring