apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rq-exporter-metrics
  labels:
    app: rq-exporter
    release: monitoring
spec:
  endpoints:
  - interval: 5s
    path: /
    port: http-metrics
  selector:
    matchLabels:
      app: rq-exporter
      release: monitoring
