apiVersion: v1
kind: Service
metadata:
  name: rq-exporter
  labels:
    app: rq-exporter
    release: monitoring
spec:
  selector:
    app: rq-exporter
    release: monitoring
  ports:
    - name: http-metrics
      port: 9726
  #clusterIP: None
status:
  loadBalancer: {}
